### ISSUE TITLE
CT: this.reset is not a function

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-line-distance#3] opened 2020-06-29 02:16 UTC
```
number-line-distance : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/number-line-distance/number-line-distance_en.html?continuousTest=%7B%22test%22%3A%5B%22number-line-distance%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1593394194354%22%2C%22timestamp%22%3A1593396314997%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught TypeError: this.reset is not a function
TypeError: this.reset is not a function
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/number-line-distance/js/explore/view/NLDExploreScreenView.js:76:14)
at ResetAllButton.options.listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/scenery-phet/js/buttons/ResetAllButton.js:62:5)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/axon/js/TinyEmitter.js:69:53)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/axon/js/Emitter.js:33:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/axon/js/Action.js:225:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/axon/js/Emitter.js:58:19)
at PushButtonModel.fire (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/sun/js/buttons/PushButtonModel.js:158:23)
at downPropertyObserver (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/sun/js/buttons/PushButtonModel.js:90:14)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/axon/js/TinyEmitter.js:69:53)
at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/axon/js/Property.js:273:25)
id: Bayes Chrome
Snapshot from 6/28/2020, 7:29:54 PM
```

**Comment by KatieWoe** [comment] 2020-06-29 14:47
Also r.reset
```
number-line-distance : fuzz : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/number-line-distance/build/phet/number-line-distance_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-line-distance%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1593394194354%22%2C%22timestamp%22%3A1593396967899%7D&fuzz&memoryLimit=1000
Query: fuzz&memoryLimit=1000
Uncaught TypeError: r.reset is not a function
TypeError: r.reset is not a function
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/number-line-distance/build/phet/number-line-distance_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-line-distance%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1593394194354%22%2C%22timestamp%22%3A1593396967899%7D&fuzz&memoryLimit=1000:912:1597084)
at t.listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/number-line-distance/build/phet/number-line-distance_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-line-distance%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1593394194354%22%2C%22timestamp%22%3A1593396967899%7D&fuzz&memoryLimit=1000:912:1027304)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/number-line-distance/build/phet/number-line-distance_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-line-distance%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1593394194354%22%2C%22timestamp%22%3A1593396967899%7D&fuzz&memoryLimit=1000:912:39699)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/number-line-distance/build/phet/number-line-distance_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-line-distance%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1593394194354%22%2C%22timestamp%22%3A1593396967899%7D&fuzz&memoryLimit=1000:912:82725
at i.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/number-line-distance/build/phet/number-line-distance_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-line-distance%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1593394194354%22%2C%22timestamp%22%3A1593396967899%7D&fuzz&memoryLimit=1000:912:62931)
at i.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/number-line-distance/build/phet/number-line-distance_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-line-distance%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1593394194354%22%2C%22timestamp%22%3A1593396967899%7D&fuzz&memoryLimit=1000:912:82928)
at kp.fire (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/number-line-distance/build/phet/number-line-distance_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-line-distance%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1593394194354%22%2C%22timestamp%22%3A1593396967899%7D&fuzz&memoryLimit=1000:912:827983)
at i (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/number-line-distance/build/phet/number-line-distance_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-line-distance%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1593394194354%22%2C%22timestamp%22%3A1593396967899%7D&fuzz&memoryLimit=1000:912:827277)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/number-line-distance/build/phet/number-line-distance_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-line-distance%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1593394194354%22%2C%22timestamp%22%3A1593396967899%7D&fuzz&memoryLimit=1000:912:39699)
at i.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593394194354/number-line-distance/build/phet/number-line-distance_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-line-distance%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1593394194354%22%2C%22timestamp%22%3A1593396967899%7D&fuzz&memoryLimit=1000:912:72169)
id: Bayes Chrome
Snapshot from 6/28/2020, 7:29:54 PM
```

**Comment by SaurabhTotey** [comment] 2020-06-29 15:25
I believe I have addressed this issue, but I'm not sure why it is complaining about an `r.reset` instead of `this.reset`. I at least removed the cause for the error of `this.reset`, but I will investigate a little more into `r.reset`.

**Comment by pixelzoom** [comment] 2020-06-29 15:36
`r.reset` is the mangled form of `this.reset` in the built version.

**Comment by jbphet** [comment] 2020-06-29 18:23
CT looks clear, and @SaurabhTotey discussed name mangling.  Closing.

**Closed by jbphet** 2020-06-29 18:23 UTC
Labels: type:automated-testing
